#!/usr/bin/env python3
"""Build the Shopping Center Operator Series v2 site data.

Reads Markdown articles (YAML front matter) from ../articles/, renders each
body with markdown-it-py (raw HTML blocks preserved for interactive widgets),
and writes assets/js/articles-data.js consumed by index.html / article.html.

Run with the default python:  python build.py
"""

import json
import re
from pathlib import Path

import yaml
from markdown_it import MarkdownIt

SITE = Path(__file__).resolve().parent
# Prefer the repo-local articles folder (self-contained repo); fall back to
# the series-level sources when building inside the larger project tree.
LOCAL = SITE / "articles"
ARTICLES_SRC = LOCAL if LOCAL.exists() else SITE.parent / "articles"
DATA_OUT = SITE / "assets" / "js" / "articles-data.js"

PARTS = [
    {"num": 1,  "roman": "I",    "name": "Owning",                     "accent": "terra"},
    {"num": 2,  "roman": "II",   "name": "Acquiring",                  "accent": "olive"},
    {"num": 3,  "roman": "III",  "name": "Financing",                  "accent": "mustard"},
    {"num": 4,  "roman": "IV",   "name": "Leasing",                    "accent": "oxblood"},
    {"num": 5,  "roman": "V",    "name": "Operating",                  "accent": "terra"},
    {"num": 6,  "roman": "VI",   "name": "Financial Management",       "accent": "olive"},
    {"num": 7,  "roman": "VII",  "name": "Marketing & Tenant Success", "accent": "mustard"},
    {"num": 8,  "roman": "VIII", "name": "Selling",                    "accent": "oxblood"},
    {"num": 9,  "roman": "IX",   "name": "Field Notes from On The Blvd", "accent": "terra"},
    {"num": 10, "roman": "X",    "name": "AI & Operating Systems",     "accent": "mustard"},
    {"num": 11, "roman": "XI",   "name": "Tools & Checklists",         "accent": "olive"},
]

md = MarkdownIt("commonmark", {"html": True}).enable("table")


def split_front_matter(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        raise ValueError("missing front matter")
    meta = yaml.safe_load(m.group(1))
    return meta, text[m.end():]


def strip_footer(body_md):
    """Drop the horizontal-rule + italic disclaimer from the rendered body;
    the template renders its own footer."""
    parts = body_md.rsplit("\n---\n", 1)
    return parts[0] if len(parts) == 2 else body_md


def main():
    articles = []
    for path in sorted(ARTICLES_SRC.glob("*.md")):
        meta, body_md = split_front_matter(path.read_text(encoding="utf-8"))
        body_html = md.render(strip_footer(body_md))
        slug = path.stem
        m = re.match(r"(\d+)-", slug)
        articles.append({
            "slug": slug,
            "num": int(m.group(1)) if m else 0,
            "title": meta["title"],
            "part": meta["part"],
            "eyebrow": meta.get("eyebrow", ""),
            "deck": meta.get("deck", ""),
            "date": meta.get("date", ""),
            "read_time": meta.get("read_time", ""),
            "feature_image": meta.get("feature_image", ""),
            "feature_caption": meta.get("feature_caption", ""),
            "interactive": 'class="ix"' in body_html,
            "body": body_html,
        })

    parts_by_name = {p["name"]: p for p in PARTS}
    payload = {
        "parts": PARTS,
        "articles": articles,
    }
    # sanity: every article part must be known
    for a in articles:
        pname = a["part"].split("—", 1)[-1].strip()
        if pname not in parts_by_name:
            raise SystemExit(f"Unknown part {a['part']!r} in {a['slug']}")

    DATA_OUT.parent.mkdir(parents=True, exist_ok=True)
    DATA_OUT.write_text(
        "// Generated by build.py — do not edit.\n"
        "window.CC_DATA = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {DATA_OUT} with {len(articles)} articles")


if __name__ == "__main__":
    main()
